# Beginning

In [2]:
%load_ext autoreload
%autoreload 2

import numpy as np
import evaluate
import warnings
import ujson
import json
import os
import sys
import time
import pandas as pd
import torch
from collections import Counter, defaultdict
from tqdm import tqdm
from itertools import chain
# Ignore all warnings
warnings.filterwarnings("ignore")

from data_module import NERDataset, NERDataModule, token_classification_collate_fn
from data_module import *
from transformers import AutoModelForTokenClassification, TrainingArguments, Trainer
from transformers import DataCollatorForTokenClassification
from torch.utils.data import DataLoader
from functools import partial
from transformers.integrations import WandbCallback
from datasets import load_dataset
from data_utils import *
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
# Load package to evaluate models
seqeval = evaluate.load("seqeval")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Create dataset for /data/

In [3]:
tag2label = {
    "ncbi_disease": tag2label_ncbi,
    "bc5cdr": tag2label_bc5cdr,
    "bc5cdr_chemical": tag2label_bc5cdr_chemical,
    "bc5cdr_disease": tag2label_bc5cdr_disease,
    "ebm_pico": tag2label_pico,
    "pico_extraction": tag2label_pico,
}

dataset_name = 'bc5cdr'
# dataset_name = 'bc5cdr_chemical'
# dataset_name = 'bc5cdr_disease'
# dataset_name = 'ncbi_disease'
# dataset_name = 'medmentions_st21pv'
# dataset_name = 'ebm_pico'
# dataset_name = 'pico_extraction'
# dataset_name = "chemprot"
dataset = load_bigbio_dataset(dataset_name)
docs = dataset_to_documents(dataset)

if dataset_name in ["ebm_pico"] :
    val_split_ids = dataset['train']['document_id'][:187]
    df = dataset_to_df(dataset=dataset, val_split_ids=val_split_ids, dataset_name = dataset_name)
elif dataset_name in ["pico_extraction"] :
    test_split_ids = dataset['train']['document_id'][:40]
    val_split_ids = dataset['train']['document_id'][40:80]
    df = dataset_to_df(dataset=dataset, val_split_ids=val_split_ids, test_split_ids=test_split_ids, dataset_name = dataset_name)
else :
    df = dataset_to_df(dataset=dataset)

In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'document_id', 'passages', 'entities', 'events', 'coreferences', 'relations'],
        num_rows: 500
    })
    test: Dataset({
        features: ['id', 'document_id', 'passages', 'entities', 'events', 'coreferences', 'relations'],
        num_rows: 500
    })
    validation: Dataset({
        features: ['id', 'document_id', 'passages', 'entities', 'events', 'coreferences', 'relations'],
        num_rows: 500
    })
})

In [5]:
df[:5]

,document_id,offsets,text,type,db_ids,split,deabbreviated_text,mention_id
0,10027919,"[[0, 16]]",22-oxacalcitriol,[Chemical],[MESH:C051883],validation,None,10027919.1
23,10027919,"[[28, 57]]",secondary hyperparathyroidism,[Disease],[MESH:D006962],validation,None,10027919.2
32,10027919,"[[75, 92]]",low bone turnover,[Disease],[MESH:D001851],validation,None,10027919.3
1,10027919,"[[106, 119]]",renal failure,[Disease],[MESH:D051437],validation,None,10027919.4
5,10027919,"[[133, 143]]",Calcitriol,[Chemical],[MESH:D002117],validation,None,10027919.5

In [185]:
# df['type'].apply(str).unique()

In [6]:
if dataset_name == 'ncbi_disease':
    for idx, row in df.iterrows():
        row['type'][0] = 'Disease'

elif dataset_name == 'bc5cdr_chemical':
    df = df[df['type'].apply(lambda x: x[0] != 'Disease')]
    
elif dataset_name == 'bc5cdr_disease':
    df = df[df['type'].apply(lambda x: x[0] != 'Chemical')]

elif dataset_name == 'ebm_pico':
    for idx, row in df.iterrows():
        if row['type'][0].startswith("Participant"):
            row['type'][0] = 'Participant'
        elif row['type'][0].startswith("Outcome"):
            row['type'][0] = 'Outcome'
        elif row['type'][0].startswith("Intervention"):
            row['type'][0] = 'Intervention'

df[:5]

,document_id,offsets,text,type,db_ids,split,deabbreviated_text,mention_id
0,10027919,"[[0, 16]]",22-oxacalcitriol,[Chemical],[MESH:C051883],validation,None,10027919.1
23,10027919,"[[28, 57]]",secondary hyperparathyroidism,[Disease],[MESH:D006962],validation,None,10027919.2
32,10027919,"[[75, 92]]",low bone turnover,[Disease],[MESH:D001851],validation,None,10027919.3
1,10027919,"[[106, 119]]",renal failure,[Disease],[MESH:D051437],validation,None,10027919.4
5,10027919,"[[133, 143]]",Calcitriol,[Chemical],[MESH:D002117],validation,None,10027919.5

In [7]:
doc_id = list(docs.keys())[0]
from IPython.display import HTML, display
display(HTML(f"<div style='white-space: pre-wrap; word-wrap: break-word;'>{docs[doc_id]}</div>"))

In [8]:
# Apply the replacement
processed_data = process_dataset(docs, df, tag2label[dataset_name])

In [9]:
pmid = df.iloc[0]['document_id']
processed_data[pmid]

{'input': '22-oxacalcitriol suppresses secondary hyperparathyroidism without inducing low bone turnover in dogs with renal failure.\nBACKGROUND: Calcitriol therapy suppresses serum levels of parathyroid hormone (PTH) in patients with renal failure but has several drawbacks, including hypercalcemia and/or marked suppression of bone turnover, which may lead to adynamic bone disease. A new vitamin D analogue, 22-oxacalcitriol (OCT), has been shown to have promising characteristics. This study was undertaken to determine the effects of OCT on serum PTH levels and bone turnover in states of normal or impaired renal function. METHODS: Sixty dogs were either nephrectomized (Nx, N = 38) or sham-operated (Sham, N = 22). The animals received supplemental phosphate to enhance PTH secretion. Fourteen weeks after the start of phosphate supplementation, half of the Nx and Sham dogs received doses of OCT (three times per week); the other half were given vehicle for 60 weeks. Thereafter, the treatment modalities for a subset of animals were crossed over for an additional eight months. Biochemical and hormonal indices of calcium and bone metabolism were measured throughout the study, and bone biopsies were done at baseline, 60 weeks after OCT or vehicle treatment, and at the end of the crossover period. RESULTS: In Nx dogs, OCT significantly decreased serum PTH levels soon after the induction of renal insufficiency. In long-standing secondary hyperparathyroidism, OCT (0.03 microg/kg) stabilized serum PTH levels during the first months. Serum PTH levels rose thereafter, but the rise was less pronounced compared with baseline than the rise seen in Nx control. These effects were accompanied by episodes of hypercalcemia and hyperphosphatemia. In animals with normal renal function, OCT induced a transient decrease in serum PTH levels at a dose of 0.1 microg/kg, which was not sustained with lowering of the doses. In Nx dogs, OCT reversed abnormal bone formation, such as woven osteoid and fibrosis, but did not significantly alter the level of bone turnover. In addition, OCT improved mineralization lag time, (that is, the rate at which osteoid mineralizes) in both Nx and Sham dogs. CONCLUSIONS: These results indicate that even though OCT does not completely prevent the occurrence of hypercalcemia in experimental dogs with renal insufficiency, it may be of use in the management of secondary hyperparathyroidism because it does not induce low bone turnover and, therefore, does not increase the risk of adynamic bone disease.',
 'output': '@@22-oxacalcitriol##Chemical@@ suppresses @@secondary hyperparathyroidism##Disease@@ without inducing @@low bone turnover##Disease@@ in dogs with @@renal failure##Disease@@.\nBACKGROUND: @@Calcitriol##Chemical@@ therapy suppresses serum levels of parathyroid hormone (PTH) in patients with @@renal failure##Disease@@ but has several drawbacks, including @@hypercalcemia##Disease@@ and/or marked @@suppression of bone turnover##Disease@@, which may lead to @@adynamic bone disease##Disease@@. A new @@vitamin D##Chemical@@ analogue, @@22-oxacalcitriol##Chemical@@ (@@OCT##Chemical@@), has been shown to have promising characteristics. This study was undertaken to determine the effects of @@OCT##Chemical@@ on serum PTH levels and bone turnover in states of normal or @@impaired renal function##Disease@@. METHODS: Sixty dogs were either nephrectomized (Nx, N = 38) or sham-operated (Sham, N = 22). The animals received supplemental @@phosphate##Chemical@@ to enhance PTH secretion. Fourteen weeks after the start of @@phosphate##Chemical@@ supplementation, half of the Nx and Sham dogs received doses of @@OCT##Chemical@@ (three times per week); the other half were given vehicle for 60 weeks. Thereafter, the treatment modalities for a subset of animals were crossed over for an additional eight months. Biochemical and hormonal indices of @@calcium##Chemical@@ and bone metabolism were measured throughout the study, and bone biopsies were done at baseline, 60 weeks after @@OCT##Chemical@@ or vehicle treatment, and at the end of the crossover period. RESULTS: In Nx dogs, @@OCT##Chemical@@ significantly decreased serum PTH levels soon after the induction of @@renal insufficiency##Disease@@. In long-standing @@secondary hyperparathyroidism##Disease@@, @@OCT##Chemical@@ (0.03 microg/kg) stabilized serum PTH levels during the first months. Serum PTH levels rose thereafter, but the rise was less pronounced compared with baseline than the rise seen in Nx control. These effects were accompanied by episodes of @@hypercalcemia##Disease@@ and @@hyperphosphatemia##Disease@@. In animals with normal renal function, @@OCT##Chemical@@ induced a transient decrease in serum PTH levels at a dose of 0.1 microg/kg, which was not sustained with lowering of the doses. In Nx dogs, @@OCT##Chemical@@ reversed abnormal bone formation, such as woven osteoid and @@fibrosis##Disease@@, but did not significantly alter the level of bone turnover. In addition, @@OCT##Chemical@@ improved mineralization lag time, (that is, the rate at which osteoid mineralizes) in both Nx and Sham dogs. CONCLUSIONS: These results indicate that even though @@OCT##Chemical@@ does not completely prevent the occurrence of @@hypercalcemia##Disease@@ in experimental dogs with @@renal insufficiency##Disease@@, it may be of use in the management of @@secondary hyperparathyroidism##Disease@@ because it does not induce @@low bone turnover##Disease@@ and, therefore, does not increase the risk of @@adynamic bone disease##Disease@@.',
 'spans': [{'start': 0,
   'end': 16,
   'label': 0,
   'tag': 'Chemical',
   'text': '22-oxacalcitriol'},
  {'start': 28,
   'end': 57,
   'label': 1,
   'tag': 'Disease',
   'text': 'secondary hyperparathyroidism'},
  {'start': 75,
   'end': 92,
   'label': 1,
   'tag': 'Disease',
   'text': 'low bone turnover'},
  {'start': 106,
   'end': 119,
   'label': 1,
   'tag': 'Disease',
   'text': 'renal failure'},
  {'start': 133,
   'end': 143,
   'label': 0,
   'tag': 'Chemical',
   'text': 'Calcitriol'},
  {'start': 222,
   'end': 235,
   'label': 1,
   'tag': 'Disease',
   'text': 'renal failure'},
  {'start': 273,
   'end': 286,
   'label': 1,
   'tag': 'Disease',
   'text': 'hypercalcemia'},
  {'start': 301,
   'end': 329,
   'label': 1,
   'tag': 'Disease',
   'text': 'suppression of bone turnover'},
  {'start': 349,
   'end': 370,
   'label': 1,
   'tag': 'Disease',
   'text': 'adynamic bone disease'},
  {'start': 378,
   'end': 387,
   'label': 0,
   'tag': 'Chemical',
   'text': 'vitamin D'},
  {'start': 398,
   'end': 414,
   'label': 0,
   'tag': 'Chemical',
   'text': '22-oxacalcitriol'},
  {'start': 416, 'end': 419, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 526, 'end': 529, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 591,
   'end': 614,
   'label': 1,
   'tag': 'Disease',
   'text': 'impaired renal function'},
  {'start': 743,
   'end': 752,
   'label': 0,
   'tag': 'Chemical',
   'text': 'phosphate'},
  {'start': 813,
   'end': 822,
   'label': 0,
   'tag': 'Chemical',
   'text': 'phosphate'},
  {'start': 887, 'end': 890, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 1110,
   'end': 1117,
   'label': 0,
   'tag': 'Chemical',
   'text': 'calcium'},
  {'start': 1230, 'end': 1233, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 1317, 'end': 1320, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 1390,
   'end': 1409,
   'label': 1,
   'tag': 'Disease',
   'text': 'renal insufficiency'},
  {'start': 1428,
   'end': 1457,
   'label': 1,
   'tag': 'Disease',
   'text': 'secondary hyperparathyroidism'},
  {'start': 1459, 'end': 1462, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 1703,
   'end': 1716,
   'label': 1,
   'tag': 'Disease',
   'text': 'hypercalcemia'},
  {'start': 1721,
   'end': 1738,
   'label': 1,
   'tag': 'Disease',
   'text': 'hyperphosphatemia'},
  {'start': 1779, 'end': 1782, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 1924, 'end': 1927, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 1988,
   'end': 1996,
   'label': 1,
   'tag': 'Disease',
   'text': 'fibrosis'},
  {'start': 2071, 'end': 2074, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 2237, 'end': 2240, 'label': 0, 'tag': 'Chemical', 'text': 'OCT'},
  {'start': 2287,
   'end': 2300,
   'label': 1,
   'tag': 'Disease',
   'text': 'hypercalcemia'},
  {'start': 2327,
   'end': 2346,
   'label': 1,
   'tag': 'Disease',
   'text': 'renal insufficiency'},
  {'start': 2386,
   'end': 2415,
   'label': 1,
   'tag': 'Disease',
   'text': 'secondary hyperparathyroidism'},
  {'start': 2443,
   'end': 2460,
   'label': 1,
   'tag': 'Disease',
   'text': 'low bone turnover'},
  {'start': 2507,
   'end': 2528,
   'label': 1,
   'tag': 'Disease',
   'text': 'adynamic bone disease'}],
 'split': 'validation'}

In [10]:
check_test_length = [pmid for pmid in processed_data.keys() if processed_data[pmid]['split']=='test']
check_valid_length = [pmid for pmid in processed_data.keys() if processed_data[pmid]['split']=='validation']
len(check_test_length), len(check_valid_length)

(500, 500)

In [12]:
with open(f"/home2/cye73/noisyNER/noisyNER/data/{dataset_name}/{dataset_name}.json", "w") as f:
    ujson.dump(processed_data, f, indent=2)

In [11]:
f"/home2/cye73/noisyNER/noisyNER/data/{dataset_name}/{dataset_name}.json"

'/home2/cye73/noisyNER/noisyNER/data/bc5cdr/bc5cdr.json'

# Create dataset for /data2/

In [13]:
def process_dataset_data2(docs, df, tag2label):
    """
    Function which modifies the abstract to include the entity:
    Input : DCTN4 as a modifier of chronic Pseudomonas aeruginosa infection
    Output : @@DCTN4##T103@@ as a modifier of @@chronic Pseudomonas aeruginosa infection##T038@@
    -------------
    docs : dict {pmid : abstract}
    df : pd.DataFrame
    """
    processed_data = []
    for pmid in docs:
        # Perform replacements based on offsets
        spans = []
        new_df = df[df["document_id"] == pmid]
        for _, row in new_df.iterrows():
            if len(row["offsets"]) > 1:
                continue
            start, end = row["offsets"][0]
            text = row["text"]
            label = tag2label[row["type"][0]]  # label
            tag = row["type"][0]
            span = {
                "start": start,
                "end": end,
                "label": label,
                "tag": tag,
                "text": text,
            }
            spans.append(span)

        processed_data.append({
            "text": docs[pmid],
            "spans": spans,
            "pmid": pmid,
            "split": row["split"],
        })
    return processed_data

In [14]:
processed_data2 = process_dataset_data2(docs, df, tag2label[dataset_name])

In [15]:
processed_data2[0]

{'text': 'Naloxone reverses the antihypertensive effect of clonidine.\nIn unanesthetized, spontaneously hypertensive rats the decrease in blood pressure and heart rate produced by intravenous clonidine, 5 to 20 micrograms/kg, was inhibited or reversed by nalozone, 0.2 to 2 mg/kg. The hypotensive effect of 100 mg/kg alpha-methyldopa was also partially reversed by naloxone. Naloxone alone did not affect either blood pressure or heart rate. In brain membranes from spontaneously hypertensive rats clonidine, 10(-8) to 10(-5) M, did not influence stereoselective binding of [3H]-naloxone (8 nM), and naloxone, 10(-8) to 10(-4) M, did not influence clonidine-suppressible binding of [3H]-dihydroergocryptine (1 nM). These findings indicate that in spontaneously hypertensive rats the effects of central alpha-adrenoceptor stimulation involve activation of opiate receptors. As naloxone and clonidine do not appear to interact with the same receptor site, the observed functional antagonism suggests the release of an endogenous opiate by clonidine or alpha-methyldopa and the possible role of the opiate in the central control of sympathetic tone.',
 'spans': [{'start': 0,
   'end': 8,
   'label': 0,
   'tag': 'Chemical',
   'text': 'Naloxone'},
  {'start': 49, 'end': 58, 'label': 0, 'tag': 'Chemical', 'text': 'clonidine'},
  {'start': 93,
   'end': 105,
   'label': 1,
   'tag': 'Disease',
   'text': 'hypertensive'},
  {'start': 181,
   'end': 190,
   'label': 0,
   'tag': 'Chemical',
   'text': 'clonidine'},
  {'start': 274,
   'end': 285,
   'label': 1,
   'tag': 'Disease',
   'text': 'hypotensive'},
  {'start': 306,
   'end': 322,
   'label': 0,
   'tag': 'Chemical',
   'text': 'alpha-methyldopa'},
  {'start': 354,
   'end': 362,
   'label': 0,
   'tag': 'Chemical',
   'text': 'naloxone'},
  {'start': 364,
   'end': 372,
   'label': 0,
   'tag': 'Chemical',
   'text': 'Naloxone'},
  {'start': 469,
   'end': 481,
   'label': 1,
   'tag': 'Disease',
   'text': 'hypertensive'},
  {'start': 487,
   'end': 496,
   'label': 0,
   'tag': 'Chemical',
   'text': 'clonidine'},
  {'start': 589,
   'end': 597,
   'label': 0,
   'tag': 'Chemical',
   'text': 'naloxone'},
  {'start': 637,
   'end': 646,
   'label': 0,
   'tag': 'Chemical',
   'text': 'clonidine'},
  {'start': 750,
   'end': 762,
   'label': 1,
   'tag': 'Disease',
   'text': 'hypertensive'},
  {'start': 865,
   'end': 873,
   'label': 0,
   'tag': 'Chemical',
   'text': 'naloxone'},
  {'start': 878,
   'end': 887,
   'label': 0,
   'tag': 'Chemical',
   'text': 'clonidine'},
  {'start': 1026,
   'end': 1035,
   'label': 0,
   'tag': 'Chemical',
   'text': 'clonidine'},
  {'start': 1039,
   'end': 1055,
   'label': 0,
   'tag': 'Chemical',
   'text': 'alpha-methyldopa'}],
 'pmid': '227508',
 'split': 'train'}

In [17]:
with open(f"/home2/cye73/noisyNER/noisyNER/data2/{dataset_name}/{dataset_name}.json", "w") as f:
    ujson.dump(processed_data2, f, indent=2)

In [16]:
f"/home2/cye73/noisyNER/noisyNER/data2/{dataset_name}/{dataset_name}.json"

'/home2/cye73/noisyNER/noisyNER/data2/bc5cdr/bc5cdr.json'

In [ ]:
# with open(f"/home2/cye73/noisyNER/noisyNER/data2/{dataset_name}/{dataset_name}.json", "r") as f:
#     processed_data_old = ujson.load(f)

In [62]:
for idx in range(len(processed_data2)):
    if processed_data2[idx] != processed_data_old[idx]:
        print(idx, processed_data2[idx]['pmid'])

8 2234245
14 2670794
20 3412544
27 3997294
80 19631624
81 20003049
84 20722491
87 322550
91 1835291
94 2054792
138 11587867
151 15458908
157 16904497
173 19957053
192 3503576
202 7053303
214 9284778
250 17854040
262 19729346
294 18821488
309 11532387
341 84204
342 9862868
349 2334618
354 230316
363 2224762
365 12483326
389 15863244
390 12921865
393 3403780
417 2375138
455 20528871
457 11928786
459 19300402
465 20477932
519 24100055
549 24618873
560 24709919
564 24733133
569 24802403
603 920167
617 19681452
618 20009434
662 1837756
665 1943082
669 2173761
680 2614930
765 7479194
766 7492040
812 9725303
823 10401555
837 10985896
843 11229942
847 11385188
854 11745287
873 12677626
879 12948256
914 16723784
933 17346443
937 17384765
983 20046642
1006 3115150
1009 2339463
1013 591536
1071 6415512
1079 18674790
1084 16428827
1094 6150641
1110 11185967
1147 16629641
1159 2322844
1166 17943461
1183 9758264
1220 8638876
1224 8643966
1225 6695415
1227 8800187
1234 20683499
1237 19721134
1238 17786501
1239 16960342
1269 9867728
1291 18356633
1318 21418164
1333 14745746
1347 4090988
1411 19274460
1416 6817363
1419 2594614
1428 11827497
1441 6615052
1452 11752998

In [64]:
processed_data_old[8]

{'text': 'Ocular and auditory toxicity in hemodialyzed patients receiving desferrioxamine.\nDuring an 18-month period of study 41 hemodialyzed patients receiving desferrioxamine (10-40 mg/kg BW/3 times weekly) for the first time were monitored for detection of audiovisual toxicity. 6 patients presented clinical symptoms of visual or auditory toxicity. Moreover, detailed ophthalmologic and audiologic studies disclosed abnormalities in 7 more asymptomatic patients. Visual toxicity was of retinal origin and was characterized by a tritan-type dyschromatopsy, sometimes associated with a loss of visual acuity and pigmentary retinal deposits. Auditory toxicity was characterized by a mid- to high-frequency neurosensorial hearing loss and the lesion was of the cochlear type. Desferrioxamine withdrawal resulted in a complete recovery of visual function in 1 patient and partial recovery in 3, and a complete reversal of hearing loss in 3 patients and partial recovery in 3. This toxicity appeared in patients receiving the higher doses of desferrioxamine or coincided with the normalization of ferritin or aluminium serum levels. The data indicate that audiovisual toxicity is not an infrequent complication in hemodialyzed patients receiving desferrioxamine. Periodical audiovisual monitoring should be performed on hemodialyzed patients receiving the drug in order to detect adverse effects as early as possible.',
 'spans': [{'start': 0,
   'end': 28,
   'label': 0,
   'tag': 'Disease',
   'text': 'Ocular and auditory toxicity'},
  {'start': 0,
   'end': 28,
   'label': 0,
   'tag': 'Disease',
   'text': 'Ocular toxicity'},
  {'start': 11,
   'end': 28,
   'label': 0,
   'tag': 'Disease',
   'text': 'auditory toxicity'},
  {'start': 64,
   'end': 79,
   'label': 1,
   'tag': 'Chemical',
   'text': 'desferrioxamine'},
  {'start': 151,
   'end': 166,
   'label': 1,
   'tag': 'Chemical',
   'text': 'desferrioxamine'},
  {'start': 250,
   'end': 270,
   'label': 0,
   'tag': 'Disease',
   'text': 'audiovisual toxicity'},
  {'start': 314,
   'end': 341,
   'label': 0,
   'tag': 'Disease',
   'text': 'visual toxicity'},
  {'start': 314,
   'end': 341,
   'label': 0,
   'tag': 'Disease',
   'text': 'visual or auditory toxicity'},
  {'start': 324,
   'end': 341,
   'label': 0,
   'tag': 'Disease',
   'text': 'auditory toxicity'},
  {'start': 457,
   'end': 472,
   'label': 0,
   'tag': 'Disease',
   'text': 'Visual toxicity'},
  {'start': 576,
   'end': 599,
   'label': 0,
   'tag': 'Disease',
   'text': 'a loss of visual acuity'},
  {'start': 604,
   'end': 631,
   'label': 0,
   'tag': 'Disease',
   'text': 'pigmentary retinal deposits'},
  {'start': 633,
   'end': 650,
   'label': 0,
   'tag': 'Disease',
   'text': 'Auditory toxicity'},
  {'start': 697,
   'end': 724,
   'label': 0,
   'tag': 'Disease',
   'text': 'neurosensorial hearing loss'},
  {'start': 766,
   'end': 781,
   'label': 1,
   'tag': 'Chemical',
   'text': 'Desferrioxamine'},
  {'start': 911,
   'end': 923,
   'label': 0,
   'tag': 'Disease',
   'text': 'hearing loss'},
  {'start': 970, 'end': 978, 'label': 0, 'tag': 'Disease', 'text': 'toxicity'},
  {'start': 1030,
   'end': 1045,
   'label': 1,
   'tag': 'Chemical',
   'text': 'desferrioxamine'},
  {'start': 1144,
   'end': 1164,
   'label': 0,
   'tag': 'Disease',
   'text': 'audiovisual toxicity'},
  {'start': 1234,
   'end': 1249,
   'label': 1,
   'tag': 'Chemical',
   'text': 'desferrioxamine'}],
 'pmid': '2234245',
 'split': 'train'}

In [58]:
processed_data2[8]

{'text': 'Comparison of three solutions of ropivacaine/fentanyl for postoperative patient-controlled epidural analgesia . BACKGROUND Ropivacaine , 0.2 % , is a new local anesthetic approved for epidural analgesia . The addition of 4 microg/ml fentanyl improves analgesia from epidural ropivacaine . Use of a lower concentration of ropivacaine-fentanyl may further improve analgesia or decrease side effects . METHODS Thirty patients undergoing lower abdominal surgery were randomized in a double-blinded manner to receive one of three solutions : 0.2 % ropivacaine-4 microg fentanyl 0.1 % ropivacaine-2 microg fentanyl , or 0.05 % ropivacaine-1 microg fentanyl for patient-controlled epidural analgesia after standardized combined epidural and general anesthesia . Patient-controlled epidural analgesia settings and adjustments for the three solutions were standardized to deliver equivalent drug doses . Pain scores ( rest , cough , and ambulation ) , side effects ( nausea , pruritus , sedation , motor block , hypotension , and orthostasis ) , and patient-controlled epidural analgesia consumption were measured for 48 h. RESULTS All three solutions produced equivalent analgesia . Motor block was significantly more common ( 30 vs. 0 % ) and more intense with the 0.2 % ropivacaine-4 microg fentanyl solution . Other side effects were equivalent between solutions and mild in severity . A significantly smaller volume of 0.2 % ropivacaine-4 microg fentanyl solution was used , whereas the 0.1 % ropivacaine-2 microg fentanyl group used a significantly greater amount of ropivacaine and fentanyl . CONCLUSIONS Lesser concentrations of ropivacaine and fentanyl provide comparable analgesia with less motor block despite the use of similar amounts of ropivacaine and fentanyl . This finding suggests that concentration of local anesthetic solution at low doses is a primary determinant of motor block with patient-controlled epidural analgesia after lower abdominal surgery .',
 'spans': [{'start': 33,
   'end': 44,
   'label': 1,
   'tag': 'Intervention',
   'text': 'ropivacaine'},
  {'start': 33,
   'end': 53,
   'label': 1,
   'tag': 'Intervention',
   'text': 'ropivacaine/fentanyl'},
  {'start': 45,
   'end': 53,
   'label': 1,
   'tag': 'Intervention',
   'text': 'fentanyl'},
  {'start': 58,
   'end': 111,
   'label': 0,
   'tag': 'Participant',
   'text': 'postoperative patient-controlled epidural analgesia .'},
  {'start': 123,
   'end': 134,
   'label': 1,
   'tag': 'Intervention',
   'text': 'Ropivacaine'},
  {'start': 321,
   'end': 341,
   'label': 1,
   'tag': 'Intervention',
   'text': 'ropivacaine-fentanyl'},
  {'start': 384,
   'end': 398,
   'label': 2,
   'tag': 'Outcome',
   'text': 'side effects .'},
  {'start': 407,
   'end': 473,
   'label': 0,
   'tag': 'Participant',
   'text': 'Thirty patients undergoing lower abdominal surgery were randomized'},
  {'start': 537,
   'end': 608,
   'label': 1,
   'tag': 'Intervention',
   'text': '0.2 % ropivacaine-4 microg fentanyl 0.1 % ropivacaine-2 microg fentanyl'},
  {'start': 543,
   'end': 556,
   'label': 1,
   'tag': 'Intervention',
   'text': 'ropivacaine-4'},
  {'start': 579,
   'end': 592,
   'label': 1,
   'tag': 'Intervention',
   'text': 'ropivacaine-2'},
  {'start': 614,
   'end': 650,
   'label': 1,
   'tag': 'Intervention',
   'text': '0.05 % ropivacaine-1 microg fentanyl'},
  {'start': 895,
   'end': 1090,
   'label': 2,
   'tag': 'Outcome',
   'text': 'Pain scores ( rest , cough , and ambulation ) , side effects ( nausea , pruritus , sedation , motor block , hypotension , and orthostasis ) , and patient-controlled epidural analgesia consumption'},
  {'start': 989,
   'end': 1000,
   'label': 2,
   'tag': 'Outcome',
   'text': 'motor block'},
  {'start': 1175,
   'end': 1186,
   'label': 2,
   'tag': 'Outcome',
   'text': 'Motor block'},
  {'start': 1370,
   'end': 1380,
   'label': 2,
   'tag': 'Outcome',
   'text': 'severity .'},
  {'start': 1865,
   'end': 1891,
   'label': 2,
   'tag': 'Outcome',
   'text': 'determinant of motor block'}],
 'pmid': '10078673',
 'split': 'validation'}

# Experiment

In [ ]:
dataset_name = "ebm_pico"
data_path = f"/home2/cye73/noisyNER/noisyNER/data2/{dataset_name}/{dataset_name}.json"
hf_model = "michiyasunaga/BioLinkBERT-base"
data_module = NERDataModule(
        data_path,
        hf_model=hf_model,
        max_length=1000,
        debug=False,
    )
data_module.setup()
train = data_module.train
validation = data_module.validation
test = data_module.test
tokenizer = data_module.tokenizer

In [ ]:
# for i in range(len(train)):
#     if len(train[i][1]) > 500:
#         print("index :", i)
#         print(len(train[i][1]))

In [21]:
data_module.split_data['train'][0]

{'text': 'DCTN4 as a modifier of chronic Pseudomonas aeruginosa infection in cystic fibrosis\nPseudomonas aeruginosa (Pa) infection in cystic fibrosis (CF) patients is associated with worse long-term pulmonary disease and shorter survival, and chronic Pa infection (CPA) is associated with reduced lung function, faster rate of lung decline, increased rates of exacerbations and shorter survival. By using exome sequencing and extreme phenotype design, it was recently shown that isoforms of dynactin 4 (DCTN4) may influence Pa infection in CF, leading to worse respiratory disease. The purpose of this study was to investigate the role of DCTN4 missense variants on Pa infection incidence, age at first Pa infection and chronic Pa infection incidence in a cohort of adult CF patients from a single centre. Polymerase chain reaction and direct sequencing were used to screen DNA samples for DCTN4 variants. A total of 121 adult CF patients from the Cochin Hospital CF centre have been included, all of them carrying two CFTR defects: 103 developed at least 1 pulmonary infection with Pa, and 68 patients of them had CPA. DCTN4 variants were identified in 24% (29/121) CF patients with Pa infection and in only 17% (3/18) CF patients with no Pa infection. Of the patients with CPA, 29% (20/68) had DCTN4 missense variants vs 23% (8/35) in patients without CPA. Interestingly, p.Tyr263Cys tend to be more frequently observed in CF patients with CPA than in patients without CPA (4/68 vs 0/35), and DCTN4 missense variants tend to be more frequent in male CF patients with CPA bearing two class II mutations than in male CF patients without CPA bearing two class II mutations (P = 0.06). Our observations reinforce that DCTN4 missense variants, especially p.Tyr263Cys, may be involved in the pathogenesis of CPA in male CF.',
 'spans': [{'start': 0, 'end': 5, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 23,
   'end': 63,
   'label': 20,
   'tag': 'T038',
   'text': 'chronic Pseudomonas aeruginosa infection'},
  {'start': 67,
   'end': 82,
   'label': 20,
   'tag': 'T038',
   'text': 'cystic fibrosis'},
  {'start': 83,
   'end': 120,
   'label': 20,
   'tag': 'T038',
   'text': 'Pseudomonas aeruginosa (Pa) infection'},
  {'start': 124,
   'end': 139,
   'label': 20,
   'tag': 'T038',
   'text': 'cystic fibrosis'},
  {'start': 141, 'end': 143, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 189,
   'end': 206,
   'label': 20,
   'tag': 'T038',
   'text': 'pulmonary disease'},
  {'start': 233,
   'end': 253,
   'label': 20,
   'tag': 'T038',
   'text': 'chronic Pa infection'},
  {'start': 255, 'end': 258, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 302,
   'end': 329,
   'label': 11,
   'tag': 'T033',
   'text': 'faster rate of lung decline'},
  {'start': 350,
   'end': 363,
   'label': 11,
   'tag': 'T033',
   'text': 'exacerbations'},
  {'start': 395,
   'end': 411,
   'label': 10,
   'tag': 'T062',
   'text': 'exome sequencing'},
  {'start': 469, 'end': 477, 'label': 5, 'tag': 'T103', 'text': 'isoforms'},
  {'start': 481, 'end': 491, 'label': 5, 'tag': 'T103', 'text': 'dynactin 4'},
  {'start': 493, 'end': 498, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 514,
   'end': 526,
   'label': 20,
   'tag': 'T038',
   'text': 'Pa infection'},
  {'start': 530, 'end': 532, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 551,
   'end': 570,
   'label': 20,
   'tag': 'T038',
   'text': 'respiratory disease'},
  {'start': 592, 'end': 597, 'label': 10, 'tag': 'T062', 'text': 'study'},
  {'start': 629, 'end': 634, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 644, 'end': 652, 'label': 5, 'tag': 'T103', 'text': 'variants'},
  {'start': 656,
   'end': 668,
   'label': 20,
   'tag': 'T038',
   'text': 'Pa infection'},
  {'start': 693,
   'end': 705,
   'label': 20,
   'tag': 'T038',
   'text': 'Pa infection'},
  {'start': 710,
   'end': 730,
   'label': 20,
   'tag': 'T038',
   'text': 'chronic Pa infection'},
  {'start': 746, 'end': 752, 'label': 4, 'tag': 'T098', 'text': 'cohort'},
  {'start': 762, 'end': 764, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 788, 'end': 794, 'label': 19, 'tag': 'T092', 'text': 'centre'},
  {'start': 796,
   'end': 821,
   'label': 10,
   'tag': 'T062',
   'text': 'Polymerase chain reaction'},
  {'start': 826,
   'end': 843,
   'label': 10,
   'tag': 'T062',
   'text': 'direct sequencing'},
  {'start': 864,
   'end': 875,
   'label': 18,
   'tag': 'T017',
   'text': 'DNA samples'},
  {'start': 880, 'end': 885, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 886, 'end': 894, 'label': 5, 'tag': 'T103', 'text': 'variants'},
  {'start': 917, 'end': 919, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 938,
   'end': 963,
   'label': 19,
   'tag': 'T092',
   'text': 'Cochin Hospital CF centre'},
  {'start': 1009, 'end': 1013, 'label': 18, 'tag': 'T017', 'text': 'CFTR'},
  {'start': 1048,
   'end': 1067,
   'label': 20,
   'tag': 'T038',
   'text': 'pulmonary infection'},
  {'start': 1073, 'end': 1075, 'label': 8, 'tag': 'T007', 'text': 'Pa'},
  {'start': 1105, 'end': 1108, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1110, 'end': 1115, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 1116, 'end': 1124, 'label': 5, 'tag': 'T103', 'text': 'variants'},
  {'start': 1157, 'end': 1159, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 1174,
   'end': 1186,
   'label': 20,
   'tag': 'T038',
   'text': 'Pa infection'},
  {'start': 1210, 'end': 1212, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 1230,
   'end': 1242,
   'label': 20,
   'tag': 'T038',
   'text': 'Pa infection'},
  {'start': 1265, 'end': 1268, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1286, 'end': 1291, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 1301, 'end': 1309, 'label': 5, 'tag': 'T103', 'text': 'variants'},
  {'start': 1344, 'end': 1347, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1364,
   'end': 1375,
   'label': 5,
   'tag': 'T103',
   'text': 'p.Tyr263Cys'},
  {'start': 1415, 'end': 1417, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 1432, 'end': 1435, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1461, 'end': 1464, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1485, 'end': 1490, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 1500, 'end': 1508, 'label': 5, 'tag': 'T103', 'text': 'variants'},
  {'start': 1542, 'end': 1544, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 1559, 'end': 1562, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1575,
   'end': 1593,
   'label': 20,
   'tag': 'T038',
   'text': 'class II mutations'},
  {'start': 1607, 'end': 1609, 'label': 20, 'tag': 'T038', 'text': 'CF'},
  {'start': 1627, 'end': 1630, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1643,
   'end': 1661,
   'label': 20,
   'tag': 'T038',
   'text': 'class II mutations'},
  {'start': 1706, 'end': 1711, 'label': 5, 'tag': 'T103', 'text': 'DCTN4'},
  {'start': 1721, 'end': 1729, 'label': 5, 'tag': 'T103', 'text': 'variants'},
  {'start': 1742,
   'end': 1753,
   'label': 5,
   'tag': 'T103',
   'text': 'p.Tyr263Cys'},
  {'start': 1778,
   'end': 1790,
   'label': 20,
   'tag': 'T038',
   'text': 'pathogenesis'},
  {'start': 1794, 'end': 1797, 'label': 20, 'tag': 'T038', 'text': 'CPA'},
  {'start': 1806, 'end': 1808, 'label': 20, 'tag': 'T038', 'text': 'CF'}],
 'pmid': '25763772',
 'split': 'train',
 'token_tags': ['O',
  'B-T103',
  'I-T103',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'I-T038',
  'I-T038',
  'O',
  'B-T038',
  'I-T038',
  'B-T038',
  'I-T038',
  'I-T038',
  'I-T038',
  'I-T038',
  'I-T038',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'I-T038',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T033',
  'I-T033',
  'I-T033',
  'I-T033',
  'I-T033',
  'O',
  'O',
  'O',
  'O',
  'B-T033',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T062',
  'I-T062',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T103',
  'O',
  'B-T103',
  'I-T103',
  'I-T103',
  'O',
  'B-T103',
  'I-T103',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T062',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T103',
  'I-T103',
  'O',
  'B-T103',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'B-T038',
  'I-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'B-T098',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'O',
  'B-T092',
  'O',
  'B-T062',
  'I-T062',
  'I-T062',
  'O',
  'B-T062',
  'I-T062',
  'O',
  'O',
  'O',
  'O',
  'B-T017',
  'I-T017',
  'O',
  'B-T103',
  'I-T103',
  'B-T103',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'B-T092',
  'I-T092',
  'I-T092',
  'I-T092',
  'I-T092',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T017',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'B-T007',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'B-T103',
  'I-T103',
  'B-T103',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T103',
  'I-T103',
  'O',
  'B-T103',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'B-T103',
  'I-T103',
  'I-T103',
  'I-T103',
  'I-T103',
  'I-T103',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T103',
  'I-T103',
  'O',
  'B-T103',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'B-T038',
  'O',
  'O',
  'B-T038',
  'I-T038',
  'I-T038',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T103',
  'I-T103',
  'O',
  'B-T103',
  'O',
  'O',
  'B-T103',
  'I-T103',
  'I-T103',
  'I-T103',
  'I-T103',
  'I-T103',
  'O',
  'O',
  'O',
  'O',
  'O',
  'O',
  'B-T038',
  'O',
  'B-T038',
  'O',
  'O',
  'B-T038',
  'O',
  'O'],
 'token_labels': [0,
  1,
  2,
  0,
  0,
  0,
  0,
  17,
  18,
  18,
  18,
  0,
  17,
  18,
  17,
  18,
  18,
  18,
  18,
  18,
  0,
  17,
  18,
  0,
  17,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  18,
  0,
  0,
  0,
  0,
  0,
  17,
  18,
  18,
  0,
  17,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  5,
  6,
  6,
  6,
  6,
  0,
  0,
  0,
  0,
  5,
  0,
  0,
  0,
  0,
  0,
  0,
  35,
  36,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  2,
  2,
  0,
  1,
  2,
  0,
  0,
  0,
  17,
  18,
  0,
  17,
  0,
  0,
  0,
  0,
  17,
  18,
  0,
  0,
  0,
  0,
  0,
  35,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  1,
  0,
  17,
  18,
  0,
  0,
  0,
  0,
  0,
  17,
  18,
  0,
  17,
  18,
  18,
  0,
  0,
  0,
  3,
  0,
  0,
  17,
  0,
  0,
  0,
  0,
  31,
  0,
  35,
  36,
  36,
  0,
  35,
  36,
  0,
  0,
  0,
  0,
  37,
  38,
  0,
  1,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  0,
  31,
  32,
  32,
  32,
  32,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  37,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  18,
  0,
  29,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  1,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  17,
  18,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  0,
  17,
  18,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  0,
  1,
  2,
  2,
  2,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  17,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  0,
  17,
  0,
  0,
  17,
  18,
  18,
  0,
  0,
  0,
  17,
  0,
  0,
  17,
  0,
  0,
  17,
  18,
  18,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  1,
  0,
  0,
  1,
  2,
  2,
  2,
  2,
  2,
  0,
  0,
  0,
  0,
  0,
  0,
  17,
  0,
  17,
  0,
  0,
  17,
  0,
  0]}

In [20]:
train[453]

('Regulation of the host immune system by helminth parasites\nHelminth parasite infections are associated with a battery of immunomodulatory mechanisms, which impact all facets of the host immune response to ensure their persistence within the host. This broad-spectrum modulation of host immunity has intended and unintended consequences, both advantageous and disadvantageous. Thus the host may benefit from suppression of collateral damage during parasite infection, and from reduced allergic, autoimmune and inflammatory reactions. However, helminth infection can also be detrimental in reducing vaccine responses, increasing susceptibility to co-infection, and potentially reducing tumor immunosurveillance. In this review we will summarize the panoply of immunomodulatory mechanisms used by helminths, their potential utility in human disease, and prospective areas of future research.',
 tensor([ 0, 17,  0,  0,  0, 21, 22,  0, 27, 27, 17, 18, 18,  0,  0,  0,  0,  0,
          0, 17, 18,  0,  0,  0,  0,  0,  0,  0,  0, 17, 18,  0,  0,  0,  0,  0,
          0,  0,  0,  0, 17, 18, 18, 18,  0,  0, 17,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13, 14,  0, 27, 17,
          0,  0,  0,  0, 17,  0, 17,  0, 17, 18,  0,  0,  0, 17, 18,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0, 19,  0, 17, 18, 18,  0,  0,  0,  0, 17, 17,
         18, 18, 18, 18,  0,  0,  0, 33,  0,  0,  0,  0,  0,  0,  0,  0, 17, 18,
          0,  0, 27, 28,  0,  0,  0,  0,  0, 27, 17,  0,  0,  0,  0,  0,  0, 35,
          0,  0]))

In [21]:
id2label = data_module.id2label
label2id = data_module.label2id
num_labels = len(id2label)

In [20]:
collate_fn = partial(token_classification_collate_fn, tokenizer=tokenizer)

In [22]:
collate_fn

functools.partial(<function token_classification_collate_fn at 0x7f6eb66af560>, tokenizer=BertTokenizerFast(name_or_path='michiyasunaga/BioLinkBERT-base', vocab_size=28895, model_max_length=1000000000000000019884624838656, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	1: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	2: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	3: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	4: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [67]:
pmid = '10526274'
data_path = '/home2/cye73/noisyNER/noisyNER/data/bc5cdr.json'
data = ujson.load(open(data_path))
for element in data:
    if element.get('pmid') == pmid:
        target_element = element
        break
    
abstract = target_element
sent_span_idxs = get_sent_boundaries(sci_nlp, abstract['text'])
split_inds = get_abstract_split(abstract, tokenizer, max_len=500)
chunks = update_offsets(abstract, split_inds)

In [98]:
split_data = defaultdict(list)
span_tags = set([])
split_names = set([])

if len(split_inds) > 1:
    chunks = update_offsets(abstract, split_inds)

    # Make sure remapings were performed corectly
    for chunk in chunks:
        text = chunk["text"]
        for span in chunk["spans"]:
            span_tags.add(span["tag"])
            assert text[span["start"] : span["end"]] == span["text"]
else:
    for span in abstract["spans"]:
        span_tags.add(span["tag"])
    chunks = [abstract]

# logger.info('Getting token-level tags for each chunk')
for chunk in chunks:
    token_tags = get_token_labels_from_char_spans(tokenizer, chunk)
    chunk["token_tags"] = token_tags

split_data[abstract["split"]].extend(chunks)
split_names.add(abstract["split"])

In [99]:
split_data['train']

[{'chunk_id': 0,
  'pmid': '10526274',
  'text': 'Gemcitabine plus vinorelbine in nonsmall cell lung carcinoma patients age 70 years or older or patients who cannot receive cisplatin. Oncopaz Cooperative Group.\nBACKGROUND: Although the prevalence of nonsmall cell lung carcinoma (NSCLC) is high among elderly patients, few data are available regarding the efficacy and toxicity of chemotherapy in this group of patients. Recent reports indicate that single agent therapy with vinorelbine (VNB) or gemcitabine (GEM) may obtain a response rate of 20-30% in elderly patients, with acceptable toxicity and improvement in symptoms and quality of life. In the current study the efficacy and toxicity of the combination of GEM and VNB in elderly patients with advanced NSCLC or those with some contraindication to receiving cisplatin were assessed. METHODS: Forty-nine patients with advanced NSCLC were included, 38 of whom were age >/= 70 years and 11 were age < 70 years but who had some contraindication to receiving cisplatin. All patients were evaluable for response and toxicity. Treatment was comprised of VNB, 25 mg/m(2), plus GEM, 1000 mg/m(2), both on Days 1, 8, and 15 every 28 days. Patients received a minimum of three courses unless progressive disease was detected. RESULTS: One hundred sixty-five courses were administered, with a median of 3. 6 courses per patient. The overall response rate was 26% (95% confidence interval, 15-41%). Two patients attained a complete response (4%) and 11 patients (22%) achieved a partial response. Eastern Cooperative Oncology Group performance status improved in 35% of those patients with an initial value > 0, whereas relief of at least 1 symptom without worsening of other symptoms was noted in 27 patients (55%). The median time to progression was 16 weeks and the 1-year survival rate was 33%. Toxicity was mild. Six patients (12%) had World Health Organization Grade 3-4 neutropenia, 2 patients (4%) had Grade 3-4 thrombocytopenia, and 2 patients (4%) had Grade 3 neurotoxicity. Three patients with severe neutropenia (6%) died of sepsis. The median age of those patients developing Grade 3-4 neutropenia was significantly higher than that of the remaining patients (75 years vs. 72 years; P = 0.047). CONCLUSIONS: The combination of GEM and VNB is moderately active and well tolerated except in patients age >/= 75 years. ',
  'spans': [{'start': 0,
    'end': 11,
    'tag': 'Chemical',
    'label': 1,
    'text': 'Gemcitabine'},
   {'start': 17,
    'end': 28,
    'tag': 'Chemical',
    'label': 1,
    'text': 'vinorelbine'},
   {'start': 32,
    'end': 60,
    'tag': 'Disease',
    'label': 0,
    'text': 'nonsmall cell lung carcinoma'},
   {'start': 123,
    'end': 132,
    'tag': 'Chemical',
    'label': 1,
    'text': 'cisplatin'},
   {'start': 200,
    'end': 228,
    'tag': 'Disease',
    'label': 0,
    'text': 'nonsmall cell lung carcinoma'},
   {'start': 230, 'end': 235, 'tag': 'Disease', 'label': 0, 'text': 'NSCLC'},
   {'start': 319,
    'end': 327,
    'tag': 'Disease',
    'label': 0,
    'text': 'toxicity'},
   {'start': 426,
    'end': 437,
    'tag': 'Chemical',
    'label': 1,
    'text': 'vinorelbine'},
   {'start': 439, 'end': 442, 'tag': 'Chemical', 'label': 1, 'text': 'VNB'},
   {'start': 447,
    'end': 458,
    'tag': 'Chemical',
    'label': 1,
    'text': 'gemcitabine'},
   {'start': 460, 'end': 463, 'tag': 'Chemical', 'label': 1, 'text': 'GEM'},
   {'start': 539,
    'end': 547,
    'tag': 'Disease',
    'label': 0,
    'text': 'toxicity'},
   {'start': 635,
    'end': 643,
    'tag': 'Disease',
    'label': 0,
    'text': 'toxicity'},
   {'start': 666, 'end': 669, 'tag': 'Chemical', 'label': 1, 'text': 'GEM'},
   {'start': 674, 'end': 677, 'tag': 'Chemical', 'label': 1, 'text': 'VNB'},
   {'start': 712, 'end': 717, 'tag': 'Disease', 'label': 0, 'text': 'NSCLC'},
   {'start': 767,
    'end': 776,
    'tag': 'Chemical',
    'label': 1,
    'text': 'cisplatin'},
   {'start': 835, 'end': 840, 'tag': 'Disease', 'label': 0, 'text': 'NSCLC'},
   {'start': 963,
    'end': 972,
    'tag': 'Chemical',
    'label': 1,
    'text': 'cisplatin'},
   {'start': 1019,
    'end': 1027,
    'tag': 'Disease',
    'label': 0,
    'text': 'toxicity'},
   {'start': 1056, 'end': 1059, 'tag': 'Chemical', 'label': 1, 'text': 'VNB'},
   {'start': 1078, 'end': 1081, 'tag': 'Chemical', 'label': 1, 'text': 'GEM'},
   {'start': 1795,
    'end': 1803,
    'tag': 'Disease',
    'label': 0,
    'text': 'Toxicity'},
   {'start': 1873,
    'end': 1884,
    'tag': 'Disease',
    'label': 0,
    'text': 'neutropenia'},
   {'start': 1916,
    'end': 1932,
    'tag': 'Disease',
    'label': 0,
    'text': 'thrombocytopenia'},
   {'start': 1966,
    'end': 1979,
    'tag': 'Disease',
    'label': 0,
    'text': 'neurotoxicity'},
   {'start': 2008,
    'end': 2019,
    'tag': 'Disease',
    'label': 0,
    'text': 'neutropenia'},
   {'start': 2033,
    'end': 2039,
    'tag': 'Disease',
    'label': 0,
    'text': 'sepsis'},
   {'start': 2095,
    'end': 2106,
    'tag': 'Disease',
    'label': 0,
    'text': 'neutropenia'},
   {'start': 2236, 'end': 2239, 'tag': 'Chemical', 'label': 1, 'text': 'GEM'},
   {'start': 2244, 'end': 2247, 'tag': 'Chemical', 'label': 1, 'text': 'VNB'}],
  'token_tags': ['O',
   'B-Chemical',
   'O',
   'B-Chemical',
   'I-Chemical',
   'I-Chemical',
   'I-Chemical',
   'O',
   'B-Disease',
   'I-Disease',
   'I-Disease',
   'I-Disease',
   'I-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'I-Disease',
   'I-Disease',
   'I-Disease',
   'I-Disease',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'I-Chemical',
   'I-Chemical',
   'I-Chemical',
   'O',
   'B-Chemical',
   'I-Chemical',
   'O',
   'O',
   'B-Chemical',
   'O',
   'B-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'O',
   'B-Chemical',
   'I-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'I-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Chemical',
   'O',
   'B-Chemical',
   'I-Chemical',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O']},
 {'chunk_id': 1,
  'pmid': '10526274',
  'text': 'This age group had an increased risk of myelosuppression. Therefore the prophylactic use of granulocyte-colony stimulating factor should be considered with this treatment. New chemotherapy combinations with higher activity and lower toxicity are needed for elderly patients with advanced NSCLC.',
  'spans': [{'start': 40,
    'end': 56,
    'tag': 'Disease',
    'label': 0,
    'text': 'myelosuppression'},
   {'start': 233,
    'end': 241,
    'tag': 'Disease',
    'label': 0,
    'text': 'toxicity'},
   {'start': 288, 'end': 293, 'tag': 'Disease', 'label': 0, 'text': 'NSCLC'}],
  'token_tags': ['O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'I-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'O',
   'B-Disease',
   'O',
   'O']}]

In [87]:
len(chunks)

2

In [94]:
def get_token_labels_from_char_spans(tokenizer, span_data: Dict[str, any]) -> List[str]:
    # Tokenize the input text and get the offset mapping
    tokenized = tokenizer(span_data["text"], return_offsets_mapping=True)

    # Create an empty list of tags, one for each token
    tags = ["O"] * len(tokenized["input_ids"])

    # Go through each span in the data
    for span in span_data["spans"]:
        span_started = False
        # Go through each offset mapping
        for i, (start, end) in enumerate(tokenized["offset_mapping"]):
            # Skip special tokens
            if start == end == 0:
                continue

            # If the start of the token is inside the span, start the span
            if start >= span["start"] and start < span["end"]:
                if not span_started:
                    tags[i] = f"B-{span['tag']}"
                    span_started = True
                else:
                    tags[i] = f"I-{span['tag']}"

            # If the token is inside the span, continue the span
            elif start < span["start"] and end > span["start"]:
                tags[i] = f"B-{span['tag']}"
                span_started = True

    return tags

In [30]:
from typing import List, Dict, Union
from transformers import PreTrainedTokenizer, DataCollatorForTokenClassification
from torch.utils.data import Dataset
import torch

class DatasetNER(Dataset):
    def __init__(self, data: List[Dict], tokenizer: PreTrainedTokenizer, label2id: Dict[str, int], max_length: int = 512, split: str = "train"):
        """
        Args:
            data (List[Dict]): The input dataset in the provided format.
            tokenizer (PreTrainedTokenizer): Tokenizer for the model.
            label2id (Dict[str, int]): Mapping of labels to integer IDs.
            max_length (int): Maximum sequence length.
            split (str): The split of the dataset ("train", "valid", "test").
        """
        self.data = [entry for entry in data if entry["split"] == split]
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.max_length = max_length
        self.inputs = []
        self.labels = []

        self._prepare_dataset()

    def _prepare_dataset(self):
        for entry in self.data:
            text = entry["text"]
            spans = entry.get("spans", [])

            # Tokenize the text
            tokenized = self.tokenizer(text, truncation=True, max_length=self.max_length, return_offsets_mapping=True)
            input_ids = tokenized["input_ids"]
            attention_mask = tokenized["attention_mask"]
            offset_mapping = tokenized["offset_mapping"]

            # Initialize labels with 'O' for all tokens
            labels = ["O"] * len(input_ids)

            # Assign labels to tokens based on spans
            for span in spans:
                span_start, span_end, tag = span["start"], span["end"], span["tag"]

                # BIO tagging (B-label for beginning, I-label for inside)
                for idx, (start, end) in enumerate(offset_mapping):
                    if start >= span_start and end <= span_end:
                        if labels[idx] == "O":  # Assign only if not labeled yet
                            if start == span_start:
                                labels[idx] = f"B-{tag}"  # Beginning of the entity
                            else:
                                labels[idx] = f"I-{tag}"  # Inside of the entity

            # Convert labels to numerical IDs
            label_ids = [self.label2id[label] if label in self.label2id else self.label2id["O"] for label in labels]

            self.inputs.append({
                "input_ids": input_ids,
                "attention_mask": attention_mask
            })
            self.labels.append(label_ids)

    def __len__(self):
        return len(self.inputs)

    def __getitem__(self, idx):
        item = self.inputs[idx]
        item["labels"] = self.labels[idx]
        return {key: torch.tensor(val) for key, val in item.items()}

def create_label2id(data: List[Dict]) -> Dict[str, int]:
    """
    Automatically create label2id mapping from dataset.

    Args:
        data (List[Dict]): The input dataset in the provided format.

    Returns:
        Dict[str, int]: Mapping of unique labels to numerical IDs.
    """
    unique_labels = {"O"}  # Start with "O" for outside tokens
    for entry in data:
        spans = entry.get("spans", [])
        for span in spans:
            tag = span["tag"]
            unique_labels.add(f"B-{tag}")  # Beginning tag
            unique_labels.add(f"I-{tag}")  # Inside tag

    # Create label2id dictionary sorted alphabetically for consistent order
    return {label: idx for idx, label in enumerate(sorted(unique_labels))}

# Usage
data_path = '/home2/cye73/noisyNER/noisyNER/data/bc5cdr.json'
data = ujson.load(open(data_path))

# Example tokenizer and label mapping
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
label2id = create_label2id(data)

# Create datasets for each split
train_dataset = DatasetNER(data, tokenizer, label2id, split="train")
valid_dataset = DatasetNER(data, tokenizer, label2id, split="valid")
test_dataset = DatasetNER(data, tokenizer, label2id, split="test")

# Example collator
collator = DataCollatorForTokenClassification(tokenizer)

# Collate batch example for train
from torch.utils.data import DataLoader
train_dataloader = DataLoader(train_dataset, batch_size=1, collate_fn=collator)

# Example batch
for batch in train_dataloader:
    print(batch)
    break

{'input_ids': tensor([[  101, 11896,  2858, 21501,  1162,  7936,  1116,  1103,  2848,  7889,
         17786,  5026,  2109,  2629,  1104,   172,  4934,  2386,  2042,   119,
          1130,  8362,  6354,  2050,  4638, 26300,   117, 20061,  1193,   177,
         24312, 27291, 13475,  1103,  9711,  1107,  1892,  2997,  1105,  1762,
          2603,  1666,  1118,  1107,  4487,  7912,  2285,   172,  4934,  2386,
          2042,   117,   126,  1106,  1406, 17599, 12139,  1116,   120,  4023,
           117,  1108,  1107, 23034,  1174,  1137, 11802,  1118,  9468,  2858,
         19315,   117,   121,   119,   123,  1106,   123, 17713,   120,  4023,
           119,  1109,   177,  1183, 11439,  5026,  2109,  2629,  1104,  1620,
         17713,   120,  4023, 11164,   118,  1899, 18873,  2572,  4163,  1108,
          1145,  6320, 11802,  1118,  9468,  2858, 21501,  1162,   119, 11896,
          2858, 21501,  1162,  2041,  1225,  1136,  6975,  1719,  1892,  2997,
          1137,  1762,  2603,   119,  1130,  3575, 10936,  1116,  1121, 20061,
          1193,   177, 24312, 27291, 13475,   172,  4934,  2386,  2042,   117,
          1275,   113,   118,   129,   114,  1106,  1275,   113,   118,   126,
           114,   150,   117,  1225,  1136,  2933, 17000, 11510, 10294,  3946,
          7861,  1104,   164,   124,  3048,   166,   118,  9468,  2858, 21501,
          1162,   113,   129,   183,  2107,   114,   117,  1105,  9468,  2858,
         21501,  1162,   117,  1275,   113,   118,   129,   114,  1106,  1275,
           113,   118,   125,   114,   150,   117,  1225,  1136,  2933,   172,
          4934,  2386,  2042,   118, 17203,  5225,  7861,  1104,   164,   124,
          3048,   166,   118,  4267,  7889, 23632,  7745, 17161,  1665,  1616,
          6451,  2042,   113,   122,   183,  2107,   114,   119,  1636,  9505,
          5057,  1115,  1107, 20061,  1193,   177, 24312, 27291, 13475,  1103,
          3154,  1104,  2129, 11164,   118,  8050,  5123, 13335, 15384,  1766,
         23842,  8803, 14915,  1104, 11769, 15045, 14392,   119,  1249,  9468,
          2858, 21501,  1162,  1105,   172,  4934,  2386,  2042,  1202,  1136,
          2845,  1106, 12254,  1114,  1103,  1269, 10814,  1751,   117,  1103,
          4379,  8458, 22904, 19867,  1863,  5401,  1103,  1836,  1104,  1126,
          1322, 19790,  2285, 11769, 15045,  1118,   172,  4934,  2386,  2042,
          1137, 11164,   118,  1899, 18873,  2572,  4163,  1105,  1103,  1936,
          1648,  1104,  1103, 11769, 15045,  1107,  1103,  2129,  1654,  1104,
         13493,  3586,   119,   102]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'labels': tensor([[0, 0, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 2, 2, 2, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 1, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0,
         2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 0, 2, 2,
         2, 2, 2, 4, 4, 4, 4, 4, 0, 2, 2, 2, 4, 0, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 3, 3, 4, 0, 2, 2, 2, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 0, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 3, 3, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 2, 2, 2, 4,
         0, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 0, 2, 2, 2, 4, 0, 2, 2, 2, 2, 2, 4, 4, 4, 4, 4,
         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0]])}

In [31]:
label2id

{'B-Chemical': 0, 'B-Disease': 1, 'I-Chemical': 2, 'I-Disease': 3, 'O': 4}

In [29]:
train_dataset[0]

{'input_ids': tensor([  101, 11896,  2858, 21501,  1162,  7936,  1116,  1103,  2848,  7889,
         17786,  5026,  2109,  2629,  1104,   172,  4934,  2386,  2042,   119,
          1130,  8362,  6354,  2050,  4638, 26300,   117, 20061,  1193,   177,
         24312, 27291, 13475,  1103,  9711,  1107,  1892,  2997,  1105,  1762,
          2603,  1666,  1118,  1107,  4487,  7912,  2285,   172,  4934,  2386,
          2042,   117,   126,  1106,  1406, 17599, 12139,  1116,   120,  4023,
           117,  1108,  1107, 23034,  1174,  1137, 11802,  1118,  9468,  2858,
         19315,   117,   121,   119,   123,  1106,   123, 17713,   120,  4023,
           119,  1109,   177,  1183, 11439,  5026,  2109,  2629,  1104,  1620,
         17713,   120,  4023, 11164,   118,  1899, 18873,  2572,  4163,  1108,
          1145,  6320, 11802,  1118,  9468,  2858, 21501,  1162,   119, 11896,
          2858, 21501,  1162,  2041,  1225,  1136,  6975,  1719,  1892,  2997,
          1137,  1762,  2603,   119,  1130,  3575, 10936,  1116,  1121, 20061,
          1193,   177, 24312, 27291, 13475,   172,  4934,  2386,  2042,   117,
          1275,   113,   118,   129,   114,  1106,  1275,   113,   118,   126,
           114,   150,   117,  1225,  1136,  2933, 17000, 11510, 10294,  3946,
          7861,  1104,   164,   124,  3048,   166,   118,  9468,  2858, 21501,
          1162,   113,   129,   183,  2107,   114,   117,  1105,  9468,  2858,
         21501,  1162,   117,  1275,   113,   118,   129,   114,  1106,  1275,
           113,   118,   125,   114,   150,   117,  1225,  1136,  2933,   172,
          4934,  2386,  2042,   118, 17203,  5225,  7861,  1104,   164,   124,
          3048,   166,   118,  4267,  7889, 23632,  7745, 17161,  1665,  1616,
          6451,  2042,   113,   122,   183,  2107,   114,   119,  1636,  9505,
          5057,  1115,  1107, 20061,  1193,   177, 24312, 27291, 13475,  1103,
          3154,  1104,  2129, 11164,   118,  8050,  5123, 13335, 15384,  1766,
         23842,  8803, 14915,  1104, 11769, 15045, 14392,   119,  1249,  9468,
          2858, 21501,  1162,  1105,   172,  4934,  2386,  2042,  1202,  1136,
          2845,  1106, 12254,  1114,  1103,  1269, 10814,  1751,   117,  1103,
          4379,  8458, 22904, 19867,  1863,  5401,  1103,  1836,  1104,  1126,
          1322, 19790,  2285, 11769, 15045,  1118,   172,  4934,  2386,  2042,
          1137, 11164,   118,  1899, 18873,  2572,  4163,  1105,  1103,  1936,
          1648,  1104,  1103, 11769, 15045,  1107,  1103,  2129,  1654,  1104,
         13493,  3586,   119,   102]),
 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 'labels': tensor([1, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 3, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
         2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 4, 4, 0, 0, 0, 0, 0, 0, 1, 2, 2,
         2, 2, 2, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 4, 4, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0,
         1, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 0, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])}

In [23]:
from torch.utils.data import Dataset
from transformers import AutoTokenizer

class DatasetNER(Dataset):
    def __init__(self, data, tokenizer, label2id, split='train', max_length=512):
        """
        Initializes the DatasetNER class.

        Args:
            data (list): List of dictionaries containing 'text' and 'spans'.
            tokenizer (transformers.PreTrainedTokenizer): Tokenizer to use.
            label2id (dict): Mapping from label strings to integer IDs.
            split (str): Dataset split to use ('train', 'validation', 'test').
            max_length (int): Maximum sequence length.
        """
        self.data = [item for item in data if item['split'] == split]
        self.tokenizer = tokenizer
        self.label2id = label2id
        self.max_length = max_length
        self.examples = self.process_data()
        
    def process_data(self):
        """
        Processes the data by tokenizing text and aligning labels.

        Returns:
            list: A list of tokenized inputs with aligned labels.
        """
        examples = []
        for item in self.data:
            text = item['text']
            spans = item['spans']
            entities = []
            for span in spans:
                entities.append({
                    'start': span['start'],
                    'end': span['end'],
                    'label': span['tag']
                })
            tokenized_input = self.tokenizer(
                text,
                truncation=True,
                max_length=self.max_length,
                return_offsets_mapping=True,
                padding='max_length'
            )
            labels = self.align_labels(tokenized_input['offset_mapping'], entities)
            tokenized_input["labels"] = labels
            # Remove offset_mapping as it's no longer needed
            tokenized_input.pop("offset_mapping")
            examples.append(tokenized_input)
        return examples

    def align_labels(self, offset_mapping, entities):
        """
        Aligns labels with tokens based on offset mappings.

        Args:
            offset_mapping (list): List of (start, end) tuples for each token.
            entities (list): List of entities with 'start', 'end', and 'label'.

        Returns:
            list: A list of label IDs aligned with the tokens.
        """
        labels = ['O'] * len(offset_mapping)
        for idx, (start, end) in enumerate(offset_mapping):
            if start == end:
                # Special token like [CLS], [SEP], or padding
                labels[idx] = -100
                continue
            for entity in entities:
                entity_start = entity['start']
                entity_end = entity['end']
                entity_label = entity['label']
                # Check if the token is within the entity span
                if start >= entity_start and end <= entity_end:
                    if start == entity_start:
                        labels[idx] = 'B-' + entity_label
                    else:
                        labels[idx] = 'I-' + entity_label
                    break  # Break if the token has been labeled
        # Convert labels to IDs
        labels = [self.label2id[label] if label != -100 else -100 for label in labels]
        return labels

    def __getitem__(self, idx):
        """
        Retrieves an item by index.

        Args:
            idx (int): Index of the item.

        Returns:
            dict: A dictionary containing tokenized inputs and labels.
        """
        return self.examples[idx]

    def __len__(self):
        """
        Returns the total number of examples.

        Returns:
            int: Number of examples.
        """
        return len(self.examples)

In [ ]:
from transformers import AutoTokenizer, DataCollatorForTokenClassification

# Sample data (replace this with your actual data)
data_path = '/home2/cye73/noisyNER/noisyNER/data2/bc5cdr.json'
data = ujson.load(open(data_path))

# Initialize tokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')

# Define label mappings
label_list = ['O', 'B-Chemical', 'I-Chemical', 'B-Disease', 'I-Disease']  # Add other labels as needed
label2id = {label: idx for idx, label in enumerate(label_list)}

# Create datasets for train, validation, and test
train_dataset = DatasetNER(data, tokenizer, label2id, split='train')
validation_dataset = DatasetNER(data, tokenizer, label2id, split='validation')
test_dataset = DatasetNER(data, tokenizer, label2id, split='test')

# Initialize data collator
data_collator = DataCollatorForTokenClassification(tokenizer)

# Example of creating DataLoaders
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_dataset, batch_size=2, collate_fn=data_collator)
validation_dataloader = DataLoader(validation_dataset, batch_size=2, collate_fn=data_collator)
test_dataloader = DataLoader(test_dataset, batch_size=2, collate_fn=data_collator)

train_dataloader = DataLoader(train_dataset, batch_size=1, collate_fn=data_collator)

# Example batch
for batch in train_dataloader:
    print(batch)
    break

{'input_ids': tensor([[  101,  6583,  4135, 22500,  2063,  7901,  2015,  1996,  3424, 10536,
          4842, 25808,  3512,  3466,  1997, 18856, 10698, 10672,  1012,  1999,
         14477,  5267, 10760, 23355,  1010, 27491, 23760, 25808,  3512, 11432,
          1996,  9885,  1999,  2668,  3778,  1998,  2540,  3446,  2550,  2011,
         26721,  8159,  3560, 18856, 10698, 10672,  1010,  1019,  2000,  2322,
         12702, 13113,  2015,  1013,  4705,  1010,  2001, 26402,  2098,  2030,
         11674,  2011,  6583,  4135, 15975,  1010,  1014,  1012,  1016,  2000,
          1016, 11460,  1013,  4705,  1012,  1996,  1044, 22571, 12184,  3619,
          3512,  3466,  1997,  2531, 11460,  1013,  4705,  6541,  1011, 25003,
          3527,  4502,  2001,  2036,  6822, 11674,  2011,  6583,  4135, 22500,
          2063,  1012,  6583,  4135, 22500,  2063,  2894,  2106,  2025,  7461,
          2593,  2668,  3778,  2030,  2540,  3446,  1012,  1999,  4167, 24972,
          2013, 27491, 23760, 25808,  3512, 11432, 18856, 10698, 10672,  1010,
          2184,  1006,  1011,  1022,  1007,  2000,  2184,  1006,  1011,  1019,
          1007,  1049,  1010,  2106,  2025,  3747, 12991, 11246, 22471,  3512,
          8031,  1997,  1031,  1017,  2232,  1033,  1011,  6583,  4135, 22500,
          2063,  1006,  1022, 13221,  1007,  1010,  1998,  6583,  4135, 22500,
          2063,  1010,  2184,  1006,  1011,  1022,  1007,  2000,  2184,  1006,
          1011,  1018,  1007,  1049,  1010,  2106,  2025,  3747, 18856, 10698,
         10672,  1011, 16081,  7028,  8031,  1997,  1031,  1017,  2232,  1033,
          1011,  4487, 10536, 22196,  2121,  3995, 26775, 22571, 10196,  1006,
          1015, 13221,  1007,  1012,  2122,  9556,  5769,  2008,  1999, 27491,
         23760, 25808,  3512, 11432,  1996,  3896,  1997,  2430,  6541,  1011,
          4748,  7389, 10085, 23606,  2953, 20858,  9125, 13791,  1997,  6728,
         13143, 13833,  1012,  2004,  6583,  4135, 22500,  2063,  1998, 18856,
         10698, 10672,  2079,  2025,  3711,  2000, 11835,  2007,  1996,  2168,
         10769,  2609,  1010,  1996,  5159,  8360, 14405, 23692, 28113,  6083,
          1996,  2713,  1997,  2019,  2203, 23924,  3560,  6728, 13143,  2011,
         18856, 10698, 10672,  2030,  6541,  1011, 25003,  3527,  4502,  1998,
          1996,  2825,  2535,  1997,  1996,  6728, 13143,  1999,  1996,  2430,
          2491,  1997, 13026,  4309,  1012,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0]]), 'labels': tensor([[-100,    1,    2,    2,    2,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    1,    2,    2,    0,    0,    0,    0,    0,    0,
            0,    0,    3,    4,    4,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    1,    2,    2,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    3,    4,    4,    4,    4,    0,    0,    0,
            0,    0,    0,    1,    2,    2,    2,    2,    0,    0,    0,    0,
            0,    1,    2,    2,    2,    0,    1,    2,    2,    2,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    3,    4,    4,    0,    1,    2,    2,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
            2,    2,    2,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    1,    2,    2,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    3,    4,    4,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    1,    2,    2,    2,    0,    1,    2,    2,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    1,    2,    2,    0,    1,    2,    2,    2,
            2,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
            0,    0,    0,    0,    0, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100]])}